name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.3, 7.4 ]
        laravel: [ 8.*, 7.*, 6.*, 5.8.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 9.*
            php: 8.0
            stability: prefer-stable
          - laravel: 8.*
            php: 8.0
            stability: prefer-stable
          - laravel: 7.*
            php: 8.0
            stability: prefer-stable
          - laravel: 6.*
            php: 8.0
            stability: prefer-stable
          - laravel: 10.*
            php: 8.1
            stability: prefer-stable
          - laravel: 9.*
            php: 8.1
            stability: prefer-stable
          - laravel: 8.*
            php: 8.1
            stability: prefer-stable
          - laravel: 10.*
            php: 8.2
            stability: prefer-stable

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: vendor/bin/phpcs

      - name: Execute tests
        run: vendor/bin/phpunit
